# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: C CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{ matrix.build_type }} on ubuntu-latest
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [release]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        submodules: recursive

    - uses: libsdl-org/setup-sdl@main
      id: sdl
      with:
        install-linux-dependencies: true
        build-type: Release
        version: 3-latest

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: true
        key: ${{ matrix.build_type }}

#     - name: configure
#       run: ./configure

#    - name: make ${{ matrix.build_type }}
#      run: make ${{ matrix.build_type }}

#     - name: make check
#       run: make check

#     - name: make distcheck
#       run: make distcheck

    - name: Build ${{ matrix.build_type }}
      run: TERM=xterm ./build.sh ${{ matrix.build_type }}
